# fly.toml app configuration file generated for backend-late-violet-8247 on 2025-08-07T19:37:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-late-violet-8247'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[services]
  internal_port = 4000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
